version: '3.1'

services:
  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - 27017:27017/tcp
    networks:
      - demo-app
  demo-app:
    build: 
      context: .
      args:
        http_proxy: $http_proxy
        https_proxy: $http_proxy
    image: demo-app
    restart: always
    networks:
      - demo-app
    ports:
      - 3001:3001
    environment:
      MONGO_URI: mongodb://mongo:27017/nodeapi
    depends_on:
      - mongo

networks:
  demo-app:
    